{
 "title": "Cluster GPU Workload Summary",
 "tags": [
  "Users",
  "RHOAI",
  "ClusterQueue",
  "Workloads",
  "GPUs"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clusterqueue",
    "label": "Cluster Queue",
    "query": {
     "query": "label_values(kueue_pending_workloads{cluster_queue!~\"garycs-cluster-queue\"},cluster_queue)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster GPU Workload Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster GPU Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster GPU Quota",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kueue_cluster_queue_nominal_quota{resource=\"nvidia.com/gpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster GPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kueue_cluster_queue_resource_usage{resource=\"nvidia.com/gpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Restricted GPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kueue_cluster_queue_lending_limit{cluster_queue=\"slack-cluster-queue\",resource=\"nvidia.com/gpu\"} == 0 or (kueue_cluster_queue_nominal_quota{cluster_queue=\"slack-cluster-queue\",resource=\"nvidia.com/gpu\"} - kueue_cluster_queue_lending_limit{cluster_queue=\"slack-cluster-queue\",resource=\"nvidia.com/gpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster GPU Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kueue_cluster_queue_resource_usage{resource=\"nvidia.com/gpu\"}) / on() sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Workloads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kueue_admitted_active_workloads{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Workloads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kueue_pending_workloads{})", "legendFormat": "__auto" }
   ]
  },
  { "title": "$clusterqueue GPU Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "clusterqueue" },
  {
   "title": "GPU Quota",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kueue_cluster_queue_nominal_quota{cluster_queue=\"$clusterqueue\", resource=\"nvidia.com/gpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kueue_cluster_queue_resource_usage{cluster_queue=\"$clusterqueue\",resource=\"nvidia.com/gpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kueue_cluster_queue_resource_usage{cluster_queue=\"$clusterqueue\",resource=\"nvidia.com/gpu\"}) / on() kueue_cluster_queue_nominal_quota{cluster_queue=\"$clusterqueue\",resource=\"nvidia.com/gpu\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Usage Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 5 },
   "targets": [
    {
     "expr": "kueue_cluster_queue_resource_usage{cluster_queue=\"$clusterqueue\",resource=\"nvidia.com/gpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "7 Day Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "avg(avg_over_time(kueue_cluster_queue_resource_usage{cluster_queue=\"$clusterqueue\",resource=\"nvidia.com/gpu\"}[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Workloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kueue_admitted_active_workloads{cluster_queue=\"$clusterqueue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Workloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kueue_pending_workloads{cluster_queue=\"$clusterqueue\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}