{
 "title": "Namespace GPU Summary",
 "description": "Dashboard that summarizes the cluster's gpu allocations and usage per namespace",
 "tags": [
  "GPU",
  "Namespace",
  "User"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{label_ete_shared_clusters_multi_tenancy_customer_namespace=\"true\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster GPU Quota Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster GPU Capacity",
   "type": "stat",
   "description": "The total available GPU's in the cluster",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GPU Quota Allocations",
   "type": "stat",
   "description": "The total of all GPUs allocated in namespace resource quotas",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.nvidia.com/gpu\", type=\"hard\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GPU Quota Requests",
   "type": "stat",
   "description": "The total of all GPUs requested in all namespaces",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.nvidia.com/gpu\", type=\"used\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU Usage by Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "Namespace" },
  {
   "title": "$Namespace GPU Capacity vs Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"$Namespace\", resource=\"requests.nvidia.com/gpu\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$Namespace Quota Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$Namespace\", resource=\"requests.nvidia.com/gpu\", type=\"used\"}) / on() kube_resourcequota{namespace=\"$Namespace\", resource=\"requests.nvidia.com/gpu\", type=\"hard\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Namespace GPU 3-Day Avg",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(kube_resourcequota{namespace=\"$Namespace\", resource=\"requests.nvidia.com/gpu\", type=\"used\"}[3d])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}