{
 "title": "kevdev",
 "description": "kevin1 development",
 "tags": [
  "kevin1",
  "dev"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "# IBM Research OpenShift GPU Summary Dashboard\n\nPanels for reviewing GPU metrics:\n  * CURRENT  - Live real-time metric data.  Data can be refreshed for updates, but time-selector has no impact.\n  * AVERAGES - Key metrics averaged over a pre-defined period of time.  Data can be refreshed, but time-selector has no impact.\n  * TRENDS   - Display metrics over a period of time, configurable by changes to the dashboard time-selector.\n\nFor details on a specific OpenShift cluster, links have been created to access locally hosted grafana dashboards."
   }
  },
  {
   "title": "Total GPUs by Cluster (Percentage)",
   "type": "piechart",
   "description": "The percentage breakdown of GPUs by Cluster",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Fmaas BACKEND"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Fmaas DEVSTAGE"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Fmaas FINETUNING"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Fmaas INSTRUCTLAB"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Premise POK"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Vela DMF"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Vela PROD"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Vela STAGING"
    }
   ]
  },
  {
   "title": "Total GPU Nodes by Cluster",
   "type": "bargauge",
   "description": "The total GPU Nodes by individual Cluster",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{label_nvidia_com_gpu_present=\"true\"})",
     "legendFormat": "Fmaas BACKEND"
    },
    {
     "expr": "count(kube_node_labels{label_nvidia_com_gpu_present=\"true\"})",
     "legendFormat": "Fmaas DEVSTAGE"
    },
    {
     "expr": "count(kube_node_labels{label_nvidia_com_gpu_present=\"true\"})",
     "legendFormat": "Fmaas FINETUNING"
    },
    {
     "expr": "count(kube_node_labels{label_nvidia_com_gpu_present=\"true\"})",
     "legendFormat": "Fmaas INSTRUCTLAB"
    },
    {
     "expr": "count(kube_node_labels{label_nvidia_com_gpu_present=\"true\"})",
     "legendFormat": "Premise POK"
    },
    {
     "expr": "count(kube_node_labels{label_nvidia_com_gpu_present=\"true\"})",
     "legendFormat": "Vela DMF"
    },
    {
     "expr": "count(kube_node_labels{label_nvidia_com_gpu_present=\"true\"})",
     "legendFormat": "Vela PROD"
    },
    {
     "expr": "count(kube_node_labels{label_nvidia_com_gpu_present=\"true\"})",
     "legendFormat": "Vela STAGING"
    }
   ]
  },
  { "title": "Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total GPU Usage by Cluster (Percentage)",
   "type": "gauge",
   "description": "The total GPU usage by individual Cluster.  This percentage calculation is requested GPUs divided by total capacity in the Cluster",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "Premise POK"
    },
    {
     "expr": "(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "Vela DMF"
    },
    {
     "expr": "(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "Vela STAGING"
    },
    {
     "expr": "(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "Vela PROD"
    },
    {
     "expr": "(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "Fmaas INSTRUCTLAB"
    },
    {
     "expr": "(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "Fmaas FINETUNING"
    },
    {
     "expr": "(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "Fmaas DEVSTAGE"
    },
    {
     "expr": "(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100",
     "legendFormat": "Fmaas BACKEND"
    }
   ]
  },
  {
   "title": "Total GPUs by Cluster (Count)",
   "type": "bargauge",
   "description": "The total GPUs by Cluster in Bar Gauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Fmaas BACKEND"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Fmaas DEVSTAGE"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Fmaas FINETUNING"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Fmaas INSTRUCTLAB"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Premise POK"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Vela DMF"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Vela PROD"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
     "legendFormat": "Vela STAGING"
    }
   ]
  },
  {
   "title": "Total GPU Usage by Cluster (Count)",
   "type": "bargauge",
   "description": "The total GPUs currently assigned to workloads by Cluster in Bar Gauge",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))",
     "legendFormat": "Fmaas BACKEND"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))",
     "legendFormat": "Fmaas DEVSTAGE"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))",
     "legendFormat": "Fmaas FINETUNING"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))",
     "legendFormat": "Fmaas INSTRUCTLAB"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))",
     "legendFormat": "Premise POK"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))",
     "legendFormat": "Vela DMF"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))",
     "legendFormat": "Vela PROD"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - (count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0))",
     "legendFormat": "Vela STAGING"
    }
   ]
  },
  {
   "title": "Free GPUs by Cluster (Count)",
   "type": "stat",
   "description": "The total of free GPUs by Cluster",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0)",
     "legendFormat": "Premise POK"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0)",
     "legendFormat": "Vela DMF"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0)",
     "legendFormat": "Vela STAGING"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0)",
     "legendFormat": "Vela PROD"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0)",
     "legendFormat": "Fmaas INSTRUCTLAB"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0)",
     "legendFormat": "Fmaas FINETUNING"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0)",
     "legendFormat": "Fmaas DEVSTAGE"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}) or vector(0)",
     "legendFormat": "Fmaas BACKEND"
    }
   ]
  },
  {
   "title": "GPU Utilization by Cluster (Current)",
   "type": "gauge",
   "description": "GPU Utilization by Cluster",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Fmaas BACKEND" },
    { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Fmaas DEVSTAGE" },
    { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Fmaas FINETUNING" },
    { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Fmaas INSTRUCTLAB" },
    { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Premise POK" },
    { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Vela DMF" },
    { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Vela PROD" },
    { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Vela STAGING" }
   ]
  },
  {
   "title": "GPU Memory Utilization by Cluster (Current)",
   "type": "gauge",
   "description": "GPU Utilization by Cluster",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Fmaas BACKEND" },
    { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Fmaas DEVSTAGE" },
    { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Fmaas FINETUNING" },
    { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Fmaas INSTRUCTLAB" },
    { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Premise POK" },
    { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Vela DMF" },
    { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Vela PROD" },
    { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Vela STAGING" }
   ]
  },
  {
   "title": "Averages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "3-Day Avg GPU Usage by Cluster (Count)",
     "type": "bargauge",
     "description": "3 Day Average GPU Usage by Cluster",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}))[3d:])",
       "legendFormat": "Fmaas BACKEND"
      },
      {
       "expr": "avg_over_time((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}))[3d:])",
       "legendFormat": "Fmaas DEVSTAGE"
      },
      {
       "expr": "avg_over_time((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}))[3d:])",
       "legendFormat": "Fmaas FINETUNING"
      },
      {
       "expr": "avg_over_time((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}))[3d:])",
       "legendFormat": "Fmaas INSTRUCTLAB"
      },
      {
       "expr": "avg_over_time((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}))[3d:])",
       "legendFormat": "Premise POK"
      },
      {
       "expr": "avg_over_time((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}))[3d:])",
       "legendFormat": "Vela DMF"
      },
      {
       "expr": "avg_over_time((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}))[3d:])",
       "legendFormat": "Vela PROD"
      },
      {
       "expr": "avg_over_time((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"}))[3d:])",
       "legendFormat": "Vela STAGING"
      }
     ]
    },
    {
     "title": "3 Day Avg GPU Usage by Cluster (Percentage)",
     "type": "gauge",
     "description": "3 Day average calculation of The total GPU usage by individual Cluster.  This percentage calculation is requested GPUs divided by total capacity in the Cluster",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100) [3d:])",
       "legendFormat": "Premise POK"
      },
      {
       "expr": "avg_over_time(((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100) [3d:])",
       "legendFormat": "Vela DMF"
      },
      {
       "expr": "avg_over_time(((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100) [3d:])",
       "legendFormat": "Vela STAGING"
      },
      {
       "expr": "avg_over_time(((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100) [3d:])",
       "legendFormat": "Vela PROD"
      },
      {
       "expr": "avg_over_time(((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100) [3d:])",
       "legendFormat": "Fmaas INSTRUCTLAB"
      },
      {
       "expr": "avg_over_time(((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100) [3d:])",
       "legendFormat": "Fmaas FINETUNING"
      },
      {
       "expr": "avg_over_time(((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100) [3d:])",
       "legendFormat": "Fmaas DEVSTAGE"
      },
      {
       "expr": "avg_over_time(((sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) * 100) [3d:])",
       "legendFormat": "Fmaas BACKEND"
      }
     ]
    }
   ]
  },
  {
   "title": "Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total GPU Usage by Cluster (Trend)",
     "type": "timeseries",
     "description": "The total GPUs currently assigned to workloads by Cluster in Trend over time format",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})",
       "legendFormat": "Fmaas BACKEND"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})",
       "legendFormat": "Fmaas DEVSTAGE"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})",
       "legendFormat": "Fmaas FINETUNING"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})",
       "legendFormat": "Fmaas INSTRUCTLAB"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})",
       "legendFormat": "Premise POK"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})",
       "legendFormat": "Vela DMF"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})",
       "legendFormat": "Vela PROD"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}) - count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=\"\"})",
       "legendFormat": "Vela STAGING"
      }
     ]
    },
    {
     "title": "GPU Utilization by Cluster",
     "type": "timeseries",
     "description": "GPU Utilization by Cluster",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
     "targets": [
      { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Fmaas BACKEND" },
      { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Fmaas DEVSTAGE" },
      { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Fmaas FINETUNING" },
      { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Fmaas INSTRUCTLAB" },
      { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Premise POK" },
      { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Vela DMF" },
      { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Vela PROD" },
      { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "Vela STAGING" }
     ]
    },
    {
     "title": "GPU Memory Utilization by Cluster",
     "type": "timeseries",
     "description": "The Average GPU Memory Utilization by Cluster for period of time",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
     "targets": [
      { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Fmaas BACKEND" },
      { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Fmaas DEVSTAGE" },
      { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Fmaas FINETUNING" },
      { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Fmaas INSTRUCTLAB" },
      { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Premise POK" },
      { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Vela DMF" },
      { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Vela PROD" },
      { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)", "legendFormat": "Vela STAGING" }
     ]
    }
   ]
  }
 ]
}