{
 "title": "VELA Cluster Monitoring v02",
 "tags": [
  "Storage",
  "Admin"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "k8s_namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "warning_threshold", "label": "PVC % Used Warning Threshold", "query": "80" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CNSA",
   "type": "stat",
   "description": "There are many things that can bring Scale CNSA to degrade state. This panel gives an overview count of how many severe errors in the last 5 minutes of the observed interval.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scale_cnsa_error_count - scale_cnsa_error_count offset 5m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Compute nodes where Scale CNSA is deployed - this panel is showing their number has been changed.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_node_info[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Config",
   "type": "stat",
   "description": "CNSA configuration has been changed.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scale_stg_error_count - scale_stg_error_count offset 5m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVCs above Warning threshold",
   "type": "stat",
   "description": "The number of PVCs having capacity usage above their warning threshold.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"} ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{namespace=~\"${k8s_namespace}\"} )) >= (${warning_threshold} / 100)) or vector (0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVCs in Pending state",
   "type": "stat",
   "description": "Compute nodes where Scale CNSA is deployed - this panel is showing their number has been changed.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=\"Pending\"}==1)) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVCs in Lost state",
   "type": "stat",
   "description": "The number of used PVCs that lost their underlying PersistentVolume. This may happen temporarily during DELETE or failures.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=\"Lost\"}==1)) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Scale CNSA error/warning/info events count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "scale_cnsa_error_count", "legendFormat": "Error" },
    { "expr": "scale_cnsa_info_count", "legendFormat": "Info" },
    { "expr": "scale_cnsa_warning_count", "legendFormat": "Warning" }
   ]
  },
  {
   "title": "Scale container status ready",
   "type": "timeseries",
   "description": "Count of Scale related containers in status ready",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{namespace='ibm-spectrum-scale'})",
     "legendFormat": "Scale"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace='ibm-spectrum-scale-csi'})",
     "legendFormat": "Scale-CSI"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace='ibm-spectrum-scale-dns'})",
     "legendFormat": "Scale-DNS"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace='ibm-spectrum-scale-operator'})",
     "legendFormat": "Scale-Operator"
    },
    {
     "expr": "count(kube_pod_container_status_ready{namespace='test-sm'})",
     "legendFormat": "Scale-Monitoring"
    }
   ]
  },
  {
   "title": "Scale container restarted",
   "type": "timeseries",
   "description": "Count of Scale related containers which has been restarted (per namespace)",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace='ibm-spectrum-scale'})",
     "legendFormat": "Scale"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace='ibm-spectrum-scale-csi'})",
     "legendFormat": "Scale-CSI"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace='ibm-spectrum-scale-dns'})",
     "legendFormat": "Scale-DNS"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace='ibm-spectrum-scale-operator'})",
     "legendFormat": "Scale-Operator"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace='test-sm'})",
     "legendFormat": "Scale-Monitoring"
    }
   ]
  },
  {
   "title": "Scale storage error/warning/info events count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "targets": [
    { "expr": "scale_stg_error_count", "legendFormat": "Error" },
    { "expr": "scale_stg_info_count", "legendFormat": "Info" },
    { "expr": "scale_stg_warning_count", "legendFormat": "Warning" }
   ]
  },
  { "title": "Cluster Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "PVCs Full in 24h - Based on daily usage",
   "type": "stat",
   "description": "The number of PVCs that may reach capacity within 24h. ",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "PVCs Full in 3 days - Based on daily usage",
   "type": "stat",
   "description": "The number of PVCs that may reach capacity within 3 days.",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "PVCs Full in 1 week - Based on daily usage",
   "type": "stat",
   "description": "The number of PVCs that may reach capacity within 1 week.",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Persistent Volume Claim (PVCs)",
   "type": "table",
   "description": "List of all Scale PVCs",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(persistentvolumeclaim, namespace, storageclass, volumename) (kube_persistentvolumeclaim_info{namespace=~\"${k8s_namespace}\"})"
    },
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{namespace=~\"${k8s_namespace}\"}/1024/1024/1024)"
    },
    {
     "expr": "(kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}/1024/1024/1024)"
    },
    {
     "expr": "(kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"}/1024/1024/1024)"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim) + sum(kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=~\"(Lost)\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "(kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}/kubelet_volume_stats_capacity_bytes{namespace=~\"${k8s_namespace}\"} * 100)"
    }
   ]
  },
  {
   "title": "Cluster Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    { "title": "Hourly Volume Usage Rate", "type": "timeseries", "gridPos": { "h": 5, "w": 21, "x": 0, "y": 18 } },
    { "title": "Daily Volume Usage Rate", "type": "timeseries", "gridPos": { "h": 5, "w": 21, "x": 0, "y": 23 } },
    { "title": "Weekly Volume Usage Rate", "type": "timeseries", "gridPos": { "h": 5, "w": 21, "x": 0, "y": 28 } }
   ]
  }
 ]
}