{
 "title": "OpenShift Nodes",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace!~\"openshift-.*|ibm-.*|nvidia-.*|kube-system|kubeflow|kyverno|mpi-operator|scheduler-plugins|.*grafana.*\"}, namespace)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health of PCIe Links Between GPUs and CPUs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Cascade Lake Servers Low PCIe BandWidth (<3.4 GB/s)",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(autopilot_health_checks{health=~\"pciebw\", node=~\".*gpu-worker.*\"}[12h])) by (node, deviceid) < 3.4"
    }
   ]
  },
  {
   "title": "IceLake  Servers Low PCIe BandWidth (<15 GB/s)",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(autopilot_health_checks{health=~\"pciebw\", node=~\".*gpu-il-worker.*\"}[12h])) by (node, deviceid) < 15.0"
    }
   ]
  },
  { "title": "Health of Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Nodes in NotReady",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=~\"Ready\", status=~\"unknown\"}>0) by (node)"
    }
   ]
  },
  {
   "title": "Nodes with Unhealthy Pods in the nvidia-gpu-operator namespace",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{} and on(pod) (kube_pod_container_status_waiting{namespace=~\"nvidia-gpu-operator\"} > 0)) by (node)"
    }
   ]
  },
  {
   "title": "# of GPU Failures",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum (kube_node_status_capacity{node=~\"$node\", resource=~\"nvidia_com_gpu\"} - kube_node_status_allocatable{node=~\"$node\", resource=~\"nvidia_com_gpu\"}) by (node) > 0"
    }
   ]
  },
  {
   "title": "GPU HW Power Brake Slowdown Active",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(autopilot_health_checks{node=~\"$node\", health=~\"power-slowdown\"} > 0) by (node)"
    }
   ]
  },
  {
   "title": "GPU Pending Row-Remapping (Sum on a node)",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(autopilot_health_checks{health=~\"remapped\", node=~\"$node\"}) by (node) > 0"
    }
   ]
  },
  {
   "title": "Multi-NIC Allocability != 2 (TCP)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(multi_nic_cni_allocability{host=~\"$node\"}) by (host) != 2"
    }
   ]
  },
  {
   "title": "Multi-NIC Connectivity != 2 (TCP)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(multi_nic_cni_connectivity{host=~\"$node\"}) by (host) != 2"
    }
   ]
  },
  { "title": "Network Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "TCP Network Received Traffic (bytes/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$node\",device=~\"en.*\"}[1m])",
     "legendFormat": "{{device}}-{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Network Transmit Traffic  (bytes/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$node\",device=~\"en.*\"}[1m])",
     "legendFormat": "{{device}}-{{instance}}"
    }
   ]
  },
  {
   "title": "RoCE/GDR RDMA Network  Receive Traffic (bytes/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_infiniband_port_data_received_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}-{{instance}}"
    }
   ]
  },
  {
   "title": "RoCE/GDR RDMA Network  Transmit Traffic (bytes/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}-{{instance}}"
    }
   ]
  },
  { "title": "Nodes Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "All Nodes Root FS Used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"/\"} * 100 / node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "All Nodes /tmp Utilization (tmpfs) on Host",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=\"tmpfs\", mountpoint=\"/tmp\", instance=~\"$node\"} - node_filesystem_avail_bytes{fstype=\"tmpfs\", mountpoint=\"/tmp\", instance=~\"$node\"})/node_filesystem_size_bytes{fstype=\"tmpfs\", mountpoint=\"/tmp\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=~\"$node\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "system-{{instance}}"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=~\"$node\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "user-{{instance}}"
    }
   ]
  },
  {
   "title": "CPU RAM Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Requested for All Pods",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "# of CPUs Requested for All Pods",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}