{
 "title": "[LIVE] OpenShift NameSpace",
 "time": { "from": "now-5m", "to": "now-1m" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL, exported_namespace)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP{exported_namespace=~\"$Namespace\"}, exported_pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Live Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[Total Cluster] Current Avg GPU Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_GPU_UTIL)" }
   ]
  },
  {
   "title": "[Total Cluster] Current GPU Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL)" }
   ]
  },
  {
   "title": "GPUs per Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "count (DCGM_FI_DEV_GPU_UTIL) by (exported_namespace)"
    }
   ]
  },
  {
   "title": "Total GPUs in Cluster",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=~\"nvidia_com_gpu\"})"
    }
   ]
  },
  {
   "title": "Total Usable GPUs in Cluster",
   "type": "stat",
   "description": "Schedulable  GPUs in Cluster",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=~\"nvidia_com_gpu\"}  unless on(node) kube_node_spec_unschedulable>0 unless on(node) kube_node_status_condition{condition=~\"Ready\", status=~\"unknown\"}>0 )"
    }
   ]
  },
  {
   "title": "Unusable GPUs in Cluster",
   "type": "stat",
   "description": "Total GPUs on cordoned nodes",
   "gridPos": { "h": 7, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=~\"nvidia_com_gpu\"} and on(node) (kube_node_spec_unschedulable>0 or kube_node_status_condition{condition=~\"Ready\", status=~\"unknown\"}>0))"
    }
   ]
  },
  {
   "title": "[Assigned GPUs] Current Avg GPU Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{exported_namespace=~\"${Namespace}\"})"
    }
   ]
  },
  {
   "title": "[Assigned GPUs] Current GPU Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL{exported_namespace=~\"${Namespace}\"})"
    }
   ]
  },
  {
   "title": "# GPUs  per PyTorchJobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(label_replace(label_replace(DCGM_FI_DEV_GPU_UTIL{}, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"), \"pod\", \"$1\", \"exported_pod\", \"(.*)\") + on(namespace, pod) group_left(created_by_name) kube_pod_info{created_by_kind=~\"PyTorchJob\"}) by (namespace, created_by_name)"
    }
   ]
  },
  {
   "title": "Current Assigned GPUs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=~\"${Namespace}\"})"
    }
   ]
  },
  {
   "title": "Current Free GPUs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=~\"nvidia_com_gpu\"}  unless on(node) kube_node_spec_unschedulable>0 unless on (node) kube_node_status_condition{condition=~\"Ready\", status=~\"unknown\"}>0) - count(label_replace(DCGM_FI_DEV_GPU_UTIL{exported_namespace=~\"${Namespace}\"}, \"node\", \"$1\", \"Hostname\", \"(.+)\") unless on(node) kube_node_spec_unschedulable>0)"
    }
   ]
  },
  {
   "title": "Avg GPU Utilization per Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg (DCGM_FI_DEV_GPU_UTIL) by (exported_namespace)"
    }
   ]
  },
  {
   "title": "Physical GPUs per Node",
   "type": "table",
   "gridPos": { "h": 43, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "count ((DCGM_FI_DEV_GPU_UTIL)) by (Hostname) \n"
    },
    {}
   ]
  },
  {
   "title": "Schedualable  GPUs per Node",
   "type": "table",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "count(label_replace(DCGM_FI_DEV_GPU_UTIL{exported_namespace=~\"\"} == 0, \"node\", \"$1\", \"Hostname\", \"(.+)\") unless on(node) kube_node_spec_unschedulable>0) by (node)"
    },
    {}
   ]
  },
  {
   "title": "Cordoned Nodes (Non Schedulable)",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable==1) by (node)"
    }
   ]
  },
  {
   "title": "GPU Utilization [Assigned]",
   "type": "graph",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{exported_namespace=~\"${Namespace}\", exported_pod=~\"${Pod}\"}",
     "legendFormat": "{{instance}} - {{device}} - {{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Current GPU Utilization [Assigned]",
   "type": "table",
   "gridPos": { "h": 38, "w": 24, "x": 0, "y": 91 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL" }
   ]
  }
 ]
}