{
 "title": "OpenShift GPU Workloads",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP, exported_namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Pod",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP{exported_namespace=~\"$namespace\"}, exported_pod)"
    }
   },
   { "name": "gpu", "label": "GPU", "query": { "query": "label_values(gpu)" } },
   {
    "name": "hostname",
    "label": "Node",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP{exported_namespace=~\"$namespace\", exported_pod=~\"$instance\"}, Hostname)"
    }
   },
   { "name": "ocp_nic", "query": "${VAR_OCP_NIC}" }
  ]
 },
 "panels": [
  {
   "title": "Busy GPUs on All Selected Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=~\"$namespace\", exported_pod=~\"$instance\"}>0)",
     "legendFormat": "# of busy GPUs"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=~\"$namespace\", exported_pod=~\"$instance\"})",
     "legendFormat": "# of total GPUs"
    }
   ]
  },
  {
   "title": "Busy GPUs on Each Selected Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_namespace=~\"$namespace\", exported_pod=~\"$instance\"}>0) by (exported_pod)",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "Mapping between Pods and Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=~\"$namespace\", pod=~\"$instance\"}) by (node, pod)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "The rate of data (bytes/sec) received over TCP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", pod=~\"${instance}\"}[1m])) by (namespace, pod, interface)",
     "legendFormat": "{{interface}}-{{pod}}"
    }
   ]
  },
  {
   "title": "The rate of data (bytes/sec) transmitted over TCP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", pod=~\"${instance}\"}[1m])) by (namespace, pod, interface)",
     "legendFormat": "{{interface}}-{{pod}}"
    }
   ]
  },
  {
   "title": "The rate of data (bytes/sec) transmitted over ROCE/GPU Direct RDMA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"${hostname}\", device=~\"mlx5_3|mlx5_4\"}[30s])",
     "legendFormat": "{{device}}-{{instance}}"
    }
   ]
  },
  {
   "title": "The rate of data (bytes/sec) received over ROCE/GPU Direct RDMA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_infiniband_port_data_received_bytes_total{instance=~\"${hostname}\", device=~\"mlx5_3|mlx5_4\"}[30s])",
     "legendFormat": "{{device}}-{{instance}}"
    }
   ]
  },
  {
   "title": "IBMON - The rate of data (bytes/sec) transmitted over ROCE/GPU Direct RDMA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_infiniband_data_transmitted_throughput{node=~\"${hostname}\", device=~\"mlx5_3|mlx5_4\"}",
     "legendFormat": "{{device}}-{{node}}"
    }
   ]
  },
  {
   "title": "IBMON - The rate of data (bytes/sec) received over ROCE/GPU Direct RDMA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_infiniband_data_received_throughput{node=~\"${hostname}\", device=~\"mlx5_3|mlx5_4\"}",
     "legendFormat": "{{device}}-{{node}}"
    }
   ]
  },
  { "title": "Health for Selected Pods/Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "# of Nodes in NotReady",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=~\"Ready\", status=~\"unknown\", node=~\"$hostname\"}>0) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "# of Nodes with Unhealthy Pods in the nvidia-gpu-operator namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{node=~\"$hostname\"} and on(pod) (kube_pod_container_status_waiting{namespace=~\"nvidia-gpu-operator\"} > 0)) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "# of GPU Failures on Nodes ( Expect  0)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_capacity{node=~\"$hostname\", resource=~\"nvidia_com_gpu\"} - kube_node_status_allocatable{node=~\"$hostname\", resource=~\"nvidia_com_gpu\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Xid Errors from the Nvidia driver",
   "type": "table",
   "description": "https://docs.nvidia.com/deploy/xid-errors/index.html#topic_4",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_XID_ERRORS{exported_namespace=~\"$namespace\", exported_pod=~\"$instance\", gpu=~\"$gpu\"} > 0) by (Hostname, exported_pod, gpu)"
    }
   ]
  },
  {
   "title": "PCIe BandWidth  (Expect 3.5+ GB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(autopilot_health_checks{health=~\"pciebw\", node=~\"$hostname\", deviceid=~\"$gpu\"}) by (deviceid, node)",
     "legendFormat": "GPU {{deviceid}}-{{node}}"
    }
   ]
  },
  {
   "title": "GPU Pending Row-Remapping (Sum on a node, Expect 0)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(autopilot_health_checks{health=~\"remapped\", node=~\"$hostname\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Multi-NIC Connectivity (Expect 2)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(multi_nic_cni_connectivity{host=~\"$hostname\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GPU Compute and Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Avg. Utilization",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"})"
      }
     ]
    },
    {
     "title": "GPU Device Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 10, "w": 18, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Device Memory Avg. Utilization",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"})"
      }
     ]
    },
    {
     "title": "GPU Device Memory Active %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_PROF_DRAM_ACTIVE{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}*100",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "The fraction of time at least one warp was active on a SM, averaged over all SM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_PROF_SM_ACTIVE{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}*100",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU FP16/32/64 and Tensor Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU FP16 Pipes Active",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_PROF_PIPE_FP16_ACTIVE{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}*100",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU FP32 Pipes Active",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_PROF_PIPE_FP32_ACTIVE{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}*100",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU FP64 Pipes Active",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_PROF_PIPE_FP64_ACTIVE{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}*100",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Tensor Core Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU PCIE and NVLink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "The Rate of Data (Bytes/sec) from device to host (DtoH)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_PROF_PCIE_TX_BYTES{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "The Rate of Data (Bytes/sec) from host to device (HtoD)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_PROF_PCIE_RX_BYTES{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "The rate of data(bytes/sec) transmitted  over NVLink, not including protocol headers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_PROF_NVLINK_TX_BYTES{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "The rate of data (bytes/sec) received over NVLink, not including protocol headers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_PROF_NVLINK_RX_BYTES{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Power and Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_TEMP{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Avg. Temp",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_GPU_TEMP{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"})"
      }
     ]
    },
    {
     "title": "GPU Power Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_DEV_POWER_USAGE{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"}",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "Total GPU Power (sum on average)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_POWER_USAGE{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"})"
      }
     ]
    },
    {
     "title": "GPU SM Clocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_DEV_SM_CLOCK{exported_pod=~\"${instance}\", gpu=~\"${gpu}\"} * 1000000",
       "legendFormat": "{{exported_pod}}-GPU {{gpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Default Cluster Network - OCP Services + IO Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Network Receive Traffic  (bytes/sec) ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$hostname\",device=~\"ens3\"}[1m])",
       "legendFormat": "{{device}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Total  Network Receive Traffic  in MB/s (sum on average)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$hostname\",device=~\"ens3\"}[1m]))/1000000"
      }
     ]
    },
    {
     "title": "TCP Network Transmit Traffic  (bytes/sec) ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$hostname\",device=~\"ens3\"}[1m])",
       "legendFormat": "{{device}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Total  Network Transmit Traffic  in MB/s (sum on average)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$hostname\",device=~\"ens3\"}[1m]))/1000000"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Root FS Used  (expected below 75%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\",instance=~\"${hostname}\"} * 100 / node_filesystem_size_bytes{mountpoint=\"/\",instance=~\"${hostname}\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node /tmp Utilization (tmpfs)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{fstype=\"tmpfs\", mountpoint=\"/tmp\", instance=~\"${hostname}\"} - node_filesystem_avail_bytes{fstype=\"tmpfs\", mountpoint=\"/tmp\", instance=~\"${hostname}\"})*100/node_filesystem_size_bytes{fstype=\"tmpfs\", mountpoint=\"/tmp\", instance=~\"${hostname}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}